/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LopHocRouteImport } from './routes/lop-hoc'
import { Route as LichPhanCongRouteImport } from './routes/lich-phan-cong'
import { Route as HocSinhRouteImport } from './routes/hoc-sinh'
import { Route as GiaoVienRouteImport } from './routes/giao-vien'
import { Route as DiemDanhRouteImport } from './routes/diem-danh'
import { Route as DichVuRouteImport } from './routes/dich-vu'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PhieuThuTaoRouteImport } from './routes/phieu-thu.tao'
import { Route as PhieuThuDanhSachRouteImport } from './routes/phieu-thu.danh-sach'
import { Route as PhieuThuDaHuyRouteImport } from './routes/phieu-thu.da-huy'
import { Route as HocPhiTaoPhieuRouteImport } from './routes/hoc-phi.tao-phieu'
import { Route as HocPhiDanhSachRouteImport } from './routes/hoc-phi.danh-sach'
import { Route as HocPhiBangGiaRouteImport } from './routes/hoc-phi.bang-gia'

const LopHocRoute = LopHocRouteImport.update({
  id: '/lop-hoc',
  path: '/lop-hoc',
  getParentRoute: () => rootRouteImport,
} as any)
const LichPhanCongRoute = LichPhanCongRouteImport.update({
  id: '/lich-phan-cong',
  path: '/lich-phan-cong',
  getParentRoute: () => rootRouteImport,
} as any)
const HocSinhRoute = HocSinhRouteImport.update({
  id: '/hoc-sinh',
  path: '/hoc-sinh',
  getParentRoute: () => rootRouteImport,
} as any)
const GiaoVienRoute = GiaoVienRouteImport.update({
  id: '/giao-vien',
  path: '/giao-vien',
  getParentRoute: () => rootRouteImport,
} as any)
const DiemDanhRoute = DiemDanhRouteImport.update({
  id: '/diem-danh',
  path: '/diem-danh',
  getParentRoute: () => rootRouteImport,
} as any)
const DichVuRoute = DichVuRouteImport.update({
  id: '/dich-vu',
  path: '/dich-vu',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PhieuThuTaoRoute = PhieuThuTaoRouteImport.update({
  id: '/phieu-thu/tao',
  path: '/phieu-thu/tao',
  getParentRoute: () => rootRouteImport,
} as any)
const PhieuThuDanhSachRoute = PhieuThuDanhSachRouteImport.update({
  id: '/phieu-thu/danh-sach',
  path: '/phieu-thu/danh-sach',
  getParentRoute: () => rootRouteImport,
} as any)
const PhieuThuDaHuyRoute = PhieuThuDaHuyRouteImport.update({
  id: '/phieu-thu/da-huy',
  path: '/phieu-thu/da-huy',
  getParentRoute: () => rootRouteImport,
} as any)
const HocPhiTaoPhieuRoute = HocPhiTaoPhieuRouteImport.update({
  id: '/hoc-phi/tao-phieu',
  path: '/hoc-phi/tao-phieu',
  getParentRoute: () => rootRouteImport,
} as any)
const HocPhiDanhSachRoute = HocPhiDanhSachRouteImport.update({
  id: '/hoc-phi/danh-sach',
  path: '/hoc-phi/danh-sach',
  getParentRoute: () => rootRouteImport,
} as any)
const HocPhiBangGiaRoute = HocPhiBangGiaRouteImport.update({
  id: '/hoc-phi/bang-gia',
  path: '/hoc-phi/bang-gia',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dich-vu': typeof DichVuRoute
  '/diem-danh': typeof DiemDanhRoute
  '/giao-vien': typeof GiaoVienRoute
  '/hoc-sinh': typeof HocSinhRoute
  '/lich-phan-cong': typeof LichPhanCongRoute
  '/lop-hoc': typeof LopHocRoute
  '/hoc-phi/bang-gia': typeof HocPhiBangGiaRoute
  '/hoc-phi/danh-sach': typeof HocPhiDanhSachRoute
  '/hoc-phi/tao-phieu': typeof HocPhiTaoPhieuRoute
  '/phieu-thu/da-huy': typeof PhieuThuDaHuyRoute
  '/phieu-thu/danh-sach': typeof PhieuThuDanhSachRoute
  '/phieu-thu/tao': typeof PhieuThuTaoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dich-vu': typeof DichVuRoute
  '/diem-danh': typeof DiemDanhRoute
  '/giao-vien': typeof GiaoVienRoute
  '/hoc-sinh': typeof HocSinhRoute
  '/lich-phan-cong': typeof LichPhanCongRoute
  '/lop-hoc': typeof LopHocRoute
  '/hoc-phi/bang-gia': typeof HocPhiBangGiaRoute
  '/hoc-phi/danh-sach': typeof HocPhiDanhSachRoute
  '/hoc-phi/tao-phieu': typeof HocPhiTaoPhieuRoute
  '/phieu-thu/da-huy': typeof PhieuThuDaHuyRoute
  '/phieu-thu/danh-sach': typeof PhieuThuDanhSachRoute
  '/phieu-thu/tao': typeof PhieuThuTaoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dich-vu': typeof DichVuRoute
  '/diem-danh': typeof DiemDanhRoute
  '/giao-vien': typeof GiaoVienRoute
  '/hoc-sinh': typeof HocSinhRoute
  '/lich-phan-cong': typeof LichPhanCongRoute
  '/lop-hoc': typeof LopHocRoute
  '/hoc-phi/bang-gia': typeof HocPhiBangGiaRoute
  '/hoc-phi/danh-sach': typeof HocPhiDanhSachRoute
  '/hoc-phi/tao-phieu': typeof HocPhiTaoPhieuRoute
  '/phieu-thu/da-huy': typeof PhieuThuDaHuyRoute
  '/phieu-thu/danh-sach': typeof PhieuThuDanhSachRoute
  '/phieu-thu/tao': typeof PhieuThuTaoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dich-vu'
    | '/diem-danh'
    | '/giao-vien'
    | '/hoc-sinh'
    | '/lich-phan-cong'
    | '/lop-hoc'
    | '/hoc-phi/bang-gia'
    | '/hoc-phi/danh-sach'
    | '/hoc-phi/tao-phieu'
    | '/phieu-thu/da-huy'
    | '/phieu-thu/danh-sach'
    | '/phieu-thu/tao'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dich-vu'
    | '/diem-danh'
    | '/giao-vien'
    | '/hoc-sinh'
    | '/lich-phan-cong'
    | '/lop-hoc'
    | '/hoc-phi/bang-gia'
    | '/hoc-phi/danh-sach'
    | '/hoc-phi/tao-phieu'
    | '/phieu-thu/da-huy'
    | '/phieu-thu/danh-sach'
    | '/phieu-thu/tao'
  id:
    | '__root__'
    | '/'
    | '/dich-vu'
    | '/diem-danh'
    | '/giao-vien'
    | '/hoc-sinh'
    | '/lich-phan-cong'
    | '/lop-hoc'
    | '/hoc-phi/bang-gia'
    | '/hoc-phi/danh-sach'
    | '/hoc-phi/tao-phieu'
    | '/phieu-thu/da-huy'
    | '/phieu-thu/danh-sach'
    | '/phieu-thu/tao'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DichVuRoute: typeof DichVuRoute
  DiemDanhRoute: typeof DiemDanhRoute
  GiaoVienRoute: typeof GiaoVienRoute
  HocSinhRoute: typeof HocSinhRoute
  LichPhanCongRoute: typeof LichPhanCongRoute
  LopHocRoute: typeof LopHocRoute
  HocPhiBangGiaRoute: typeof HocPhiBangGiaRoute
  HocPhiDanhSachRoute: typeof HocPhiDanhSachRoute
  HocPhiTaoPhieuRoute: typeof HocPhiTaoPhieuRoute
  PhieuThuDaHuyRoute: typeof PhieuThuDaHuyRoute
  PhieuThuDanhSachRoute: typeof PhieuThuDanhSachRoute
  PhieuThuTaoRoute: typeof PhieuThuTaoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/lop-hoc': {
      id: '/lop-hoc'
      path: '/lop-hoc'
      fullPath: '/lop-hoc'
      preLoaderRoute: typeof LopHocRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lich-phan-cong': {
      id: '/lich-phan-cong'
      path: '/lich-phan-cong'
      fullPath: '/lich-phan-cong'
      preLoaderRoute: typeof LichPhanCongRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hoc-sinh': {
      id: '/hoc-sinh'
      path: '/hoc-sinh'
      fullPath: '/hoc-sinh'
      preLoaderRoute: typeof HocSinhRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/giao-vien': {
      id: '/giao-vien'
      path: '/giao-vien'
      fullPath: '/giao-vien'
      preLoaderRoute: typeof GiaoVienRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diem-danh': {
      id: '/diem-danh'
      path: '/diem-danh'
      fullPath: '/diem-danh'
      preLoaderRoute: typeof DiemDanhRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dich-vu': {
      id: '/dich-vu'
      path: '/dich-vu'
      fullPath: '/dich-vu'
      preLoaderRoute: typeof DichVuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/phieu-thu/tao': {
      id: '/phieu-thu/tao'
      path: '/phieu-thu/tao'
      fullPath: '/phieu-thu/tao'
      preLoaderRoute: typeof PhieuThuTaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/phieu-thu/danh-sach': {
      id: '/phieu-thu/danh-sach'
      path: '/phieu-thu/danh-sach'
      fullPath: '/phieu-thu/danh-sach'
      preLoaderRoute: typeof PhieuThuDanhSachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/phieu-thu/da-huy': {
      id: '/phieu-thu/da-huy'
      path: '/phieu-thu/da-huy'
      fullPath: '/phieu-thu/da-huy'
      preLoaderRoute: typeof PhieuThuDaHuyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hoc-phi/tao-phieu': {
      id: '/hoc-phi/tao-phieu'
      path: '/hoc-phi/tao-phieu'
      fullPath: '/hoc-phi/tao-phieu'
      preLoaderRoute: typeof HocPhiTaoPhieuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hoc-phi/danh-sach': {
      id: '/hoc-phi/danh-sach'
      path: '/hoc-phi/danh-sach'
      fullPath: '/hoc-phi/danh-sach'
      preLoaderRoute: typeof HocPhiDanhSachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hoc-phi/bang-gia': {
      id: '/hoc-phi/bang-gia'
      path: '/hoc-phi/bang-gia'
      fullPath: '/hoc-phi/bang-gia'
      preLoaderRoute: typeof HocPhiBangGiaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DichVuRoute: DichVuRoute,
  DiemDanhRoute: DiemDanhRoute,
  GiaoVienRoute: GiaoVienRoute,
  HocSinhRoute: HocSinhRoute,
  LichPhanCongRoute: LichPhanCongRoute,
  LopHocRoute: LopHocRoute,
  HocPhiBangGiaRoute: HocPhiBangGiaRoute,
  HocPhiDanhSachRoute: HocPhiDanhSachRoute,
  HocPhiTaoPhieuRoute: HocPhiTaoPhieuRoute,
  PhieuThuDaHuyRoute: PhieuThuDaHuyRoute,
  PhieuThuDanhSachRoute: PhieuThuDanhSachRoute,
  PhieuThuTaoRoute: PhieuThuTaoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
